version: "3"
services:
  mysql:
    image: "mysql:8"
    ports:
      - "8081:3306"
    environment:
      MYSQL_USER: knex_cleaner
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: knex_cleaner_test
      MYSQL_RANDOM_ROOT_PASSWORD: 1
  postgres:
    image: "postgres:9"
    ports:
      - "8082:5432"
    environment:
      POSTGRES_DB: knex_cleaner_test
      POSTGRES_USER: knex_cleaner
      POSTGRES_PASSWORD: password
